# Generated by Django 2.1.1 on 2018-11-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('idCuenta', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('habilitada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('idTipoDocumento', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombreDocumento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.TipoDocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('Identificador', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('numeroDocumento', models.CharField(blank=True, max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('encargado', models.ManyToManyField(through='Usuario.Encargado', to='Usuario.Usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='usuario_documento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuarios'),
        ),
        migrations.AddField(
            model_name='tipousuario',
            name='rolUsuario',
            field=models.ManyToManyField(through='Usuario.RolUsuario', to='Usuario.Usuarios'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='usuario_Documento',
            field=models.ManyToManyField(through='Usuario.Usuario_Documento', to='Usuario.Usuarios'),
        ),
        migrations.AddField(
            model_name='rolusuario',
            name='tipoUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.TipoUsuario'),
        ),
        migrations.AddField(
            model_name='rolusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuarios'),
        ),
        migrations.AddField(
            model_name='encargado',
            name='idEncargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idEncargado', to='Usuario.Usuarios'),
        ),
        migrations.AddField(
            model_name='encargado',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idUsuario', to='Usuario.Usuarios'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuarios'),
        ),
    ]
