# Generated by Django 2.1.1 on 2018-11-05 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manilla',
            fields=[
                ('macId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manilla_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField()),
                ('manilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Manilla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='manilla',
            name='manilla_Usuario',
            field=models.ManyToManyField(through='Usuario.Manilla_Usuario', to='Usuario.Usuarios'),
        ),
    ]
