# Generated by Django 2.1.1 on 2018-11-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_auto_20181105_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manilla_App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField()),
                ('appMovil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.AppMovil')),
                ('manilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Manilla')),
            ],
        ),
        migrations.AddField(
            model_name='appmovil',
            name='manilla_App',
            field=models.ManyToManyField(through='Usuario.Manilla_App', to='Usuario.Manilla'),
        ),
    ]
