# Generated by Django 2.1.1 on 2018-12-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_auto_20181118_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='fechaNacimiento',
        ),
    ]
