# Generated by Django 2.1.1 on 2018-11-05 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_auto_20181105_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.AppMovil')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePermiso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Permiso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='permiso',
            name='manilla_App',
            field=models.ManyToManyField(through='Usuario.Permiso_Usuario', to='Usuario.Usuarios'),
        ),
    ]
