# Generated by Django 2.1.1 on 2018-11-05 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_auto_20181105_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permiso',
            old_name='manilla_App',
            new_name='Usuario',
        ),
    ]
