# Generated by Django 2.1.1 on 2018-11-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0006_auto_20181105_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarma',
            old_name='usuario',
            new_name='appMovil',
        ),
    ]
