# Generated by Django 2.1.1 on 2018-11-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_auto_20181105_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarma',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alarma',
            name='solucionado',
            field=models.BooleanField(default=False),
        ),
    ]
